### ISSUE TITLE
How to name output image file extension?

### ISSUE THREAD

**Issue by jeffjensen** [mthmulders/puml-maven-plugin#23]
Hi, the plugin writes the output PNG file with the same name as the input file.  What is the trick to have it set the extension to png?

**Comment by mthmulders** [comment]
Hi Jeff, thanks for reaching out. I'm not exactly sure if I understand correctly what you want to know. As the [tests demonstrate](https://github.com/mthmulders/puml-maven-plugin/blob/main/tests/src/test/java/it/mulders/puml/tests/BasicUsageIT.java), if your input file is **example.puml**, and the format is **PNG**, then the output file is **example.png**.

Is there anything else you would like to happen in that case?

**Comment by jeffjensen** [comment]
Hi Maarten, thank you for the reply.

That's what I expected but is not happening.  For example, `class-diagram.plantuml` ends up as `class-diagram.plantuml` in the output directory.  It is an image tho, just the wrong name.

Probably I have a configuration issue.  Would you mind reviewing it please and advising?

```
    <plantuml-maven-plugin.version>0.1</plantuml-maven-plugin.version>
    <plantuml.version>1.2021.2</plantuml.version>
...
        <plugin>
          <groupId>it.mulders.puml</groupId>
          <artifactId>plantuml-maven-plugin</artifactId>
          <version>${plantuml-maven-plugin.version}</version>
          <dependencies>
          <dependency>
            <groupId>it.mulders.puml</groupId>
            <artifactId>plantuml-v1-adapter</artifactId>
            <version>${plantuml-maven-plugin.version}</version>
          </dependency>
          <dependency>
            <groupId>net.sourceforge.plantuml</groupId>
            <artifactId>plantuml</artifactId>
            <version>${plantuml.version}</version>
          </dependency>
          </dependencies>
          <configuration>
            <sourceFiles>
              <directory>${project.build.directory}/generated-docs</directory>
              <includes>
                <include>**/*.plantuml</include>
              </includes>
            </sourceFiles>
            <outputDirectory>${project.reporting.outputDirectory}</outputDirectory>
            <format>PNG</format>
            <stripPath>${project.build.directory}/generated-docs</stripPath>
          </configuration>
        </plugin>
```

**Comment by mthmulders** [comment]
Ah, thanks, that provides some insights. I think it has to do with the fact that you take source files from **target/**. I will look at it further but I think the plugin should support that situation as well :-)

**Comment by jeffjensen** [comment]
Ok thanks!  Agreed should support any extension user specifies.

Nice to know that I can temporarily rename to make it work.

**Comment by mthmulders** [comment]
@jeffjensen, could you double-check that the integration test in the aforementioned PR is like your use case?

**Comment by jeffjensen** [comment]
Looks good!!  Thank you very much for working on it so immediately.

**Comment by jeffjensen** [comment]
Hi, for my planning, wondering what is your timing for the next release containing this change?

**Comment by mthmulders** [comment]
> Hi, for my planning, wondering what is your timing for the next release containing this change?

I was waiting to see if #26 would turn out to be a bug as well... But come to think of it, cutting a release isn't that much work. [Release 0.2](https://github.com/mthmulders/puml-maven-plugin/releases/tag/v0.2) is syncing to Central as we speak. Enjoy the release - and spread the word ;-).

**Comment by jeffjensen** [comment]
> waiting to see if #26 would turn out to be a bug as well...

Ah yes, I haven't made time to further work on that one yet.

> Release 0.2 is syncing to Central as we speak

Most excellent, thank you!  Allows me to merge these changes.  Will work on #26 soon.
